"""add admin cities room types

Revision ID: 026f413b88cb
Revises: cb38a64cda58
Create Date: 2026-10-04 19:54:22.418308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '026f413b88cb'
down_revision: Union[str, Sequence[str], None] = 'cb38a64cda58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('room_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('hotels', sa.Column('city_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'hotels', 'cities', ['city_id'], ['id'])
    op.drop_column('hotels', 'city')
    op.add_column('rooms', sa.Column('room_type_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'rooms', 'room_types', ['room_type_id'], ['id'])
    op.drop_column('rooms', 'room_type')
    op.add_column('users', sa.Column('role', sa.String(length=50), server_default='user', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.add_column('rooms', sa.Column('room_type', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.drop_column('rooms', 'room_type_id')
    op.add_column('hotels', sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'hotels', type_='foreignkey')
    op.drop_column('hotels', 'city_id')
    op.drop_table('room_types')
    op.drop_table('cities')
    # ### end Alembic commands ###
